// Auto-generated by compileCache - DO NOT EDIT MANUALLY

function renderHtml(html: string, props: Record<string, any>): string {
  let res = html;
  for (const [k, v] of Object.entries(props)) {
    res = res.split(`{{${k}}}`).join(v != null ? String(v) : "");
  }
  return res;
}

