name = "poc-backend"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

# Serve static files from the ./public directory at the Cloudflare Edge
[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f3d47265-97b0-4399-b0d0-3761b522e680" # Created via: npx wrangler d1 create studio-db

[[kv_namespaces]]
binding = "PAGE_CACHE"
id = "62705a56a0f745e985b2d712e8653903" # Put a placeholder or real KV ID here

