# Top-Level / Default (Production)
name = "my-app-testing"
main = "src/index.ts"
compatibility_date = "2026-09-01"

# Production D1 Database
[[d1_databases]]
binding = "DB"
database_name = "prod"
database_id = "c04dda39-26b4-4948-8dfc-ac33aa283ff4"

# Production KV Namespace
[[kv_namespaces]]
binding = "PAGE_CACHE"
id = "PAGE_CACHE"

# -----------------------------------------------------------------------------
# Staging Environment Overrides (`bunx wrangler deploy -e staging`)
# -----------------------------------------------------------------------------
[env.staging]
name = "my-app-staging"

# Staging D1 Database
[[env.staging.d1_databases]]
binding = "DB"
database_name = "test"
database_id = "20d92b02-8f65-4e87-83d4-2fb8b57d5a1f"

# Staging KV Namespace
[[env.staging.kv_namespaces]]
binding = "PAGE_CACHE"
id = "62705a56a0f745e985b2d712e8653903"