import { readAndExpandTemplate } from "./readAndExpandTemplate.js";
import { compileStylesheets } from "./css.js";
import fs from "fs";

const compileCache = () => {
  compileStylesheets();

  // Generate TypeScript code
  let tsCode = `// Auto-generated by compileCache - DO NOT EDIT MANUALLY\n\n`;

  // Generic render function helper
  tsCode += `function renderHtml(html: string, props: Record<string, any>): string {\n`;
  tsCode += `  let res = html;\n`;
  tsCode += `  for (const [k, v] of Object.entries(props)) {\n`;
  tsCode += `    res = res.split(\`{{\${k}}}\`).join(v != null ? String(v) : "");\n`;
  tsCode += `  }\n`;
  tsCode += `  return res;\n`;
  tsCode += `}\n\n`;

  fs.writeFileSync("./templateCache.ts", tsCode);

  console.log("✓ Successfully generated typed renderers in templateCache.ts");
};

compileCache();
