import { readAndExpandTemplate } from "./readAndExpandTemplate.js";
import { compileStylesheets } from "./css.js";
import fs from "fs";

const compileCache = () => {
  compileStylesheets();
  const cache = {
    PrivateDashboard: readAndExpandTemplate(
      "/private/renderPrivateDashboard/PrivateDashboard.html",
    ),
    PrivatePerformanceCard: readAndExpandTemplate(
      "/private/renderPrivateDashboard/PrivatePerformanceCard.html",
    ),
    PrivatePerformance: readAndExpandTemplate(
      "/private/renderPrivatePerformance/PrivatePerformance.html",
    ),
    PrivateSegmentCard: readAndExpandTemplate(
      "/private/renderPrivatePerformance/PrivateSegmentCard.html",
    ),
    Claim: readAndExpandTemplate("/private/renderClaim/Claim.html"),
    PublicPortfolio: readAndExpandTemplate(
      "/public/renderPublicPortfolio/PublicPortfolio.html",
    ),
    PublicPerformanceCard: readAndExpandTemplate(
      "/public/renderPublicPortfolio/PublicPerformanceCard.html",
    ),
    PublicPerformance: readAndExpandTemplate(
      "/public/renderPublicPerformance/PublicPerformance.html",
    ),
    PublicSegmentCard: readAndExpandTemplate(
      "/public/renderPublicPerformance/PublicSegmentCard.html",
    ),
    PlaylistSegmentCard: readAndExpandTemplate(
      "/playlist/renderPlaylist/PlaylistSegmentCard.html",
    ),
    Playlist: readAndExpandTemplate("/playlist/renderPlaylist/Playlist.html"),
    PlaylistPerformanceCard: readAndExpandTemplate(
      "/playlist/playlistList/PlaylistPerformanceCard.html",
    ),
    PublicSideBar: readAndExpandTemplate(
      "/public/renderPublicPerformance/PublicViewSidebar.html",
    ),
    MyPlaylists: readAndExpandTemplate(
      "/playlist/playlistList/PlaylistPortfolio.html",
    ),
    Missing: readAndExpandTemplate("/public/Missing.html"),
    Graph: readAndExpandTemplate("/graph/Graph.html"),
  };

  // Write template string literals as const so TypeScript can inspect {{placeholders}}
  const tsContent = `// Auto-generated by compileCache - DO NOT EDIT MANUALLY
export const templateCache = ${JSON.stringify(cache, null, 2)} as const;
`;

  fs.writeFileSync("./templateCache.ts", tsContent);
  fs.writeFileSync("./templateCache.json", JSON.stringify(cache));
  fs.writeFileSync(
    "./public/feed.html",
    readAndExpandTemplate("/feed/Feed.html"),
  );

  console.log("✓ Built templateCache.json and type-safe templateCache.ts");
};

compileCache();
